-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 05, 2020 at 02:25 PM
-- Server version: 10.4.13-MariaDB
-- PHP Version: 7.4.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `indian_science`
--

-- --------------------------------------------------------

--
-- Table structure for table `publications`
--

CREATE TABLE `publications` (
  `id` int(11) NOT NULL,
  `title` varchar(500) NOT NULL,
  `author` varchar(400) NOT NULL,
  `journal` varchar(300) NOT NULL,
  `year` year(4) NOT NULL,
  `doi` varchar(50) NOT NULL,
  `url` text NOT NULL,
  `abstract` text NOT NULL,
  `vol` varchar(10) NOT NULL,
  `issue` varchar(10) NOT NULL,
  `page` varchar(20) NOT NULL,
  `category` varchar(400) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `publications`
--

INSERT INTO `publications` (`id`, `title`, `author`, `journal`, `year`, `doi`, `url`, `abstract`, `vol`, `issue`, `page`, `category`) VALUES
(1, 'The Case of Significant Variations in Gold-Green and Black Open Access: Evidence from Indian Research Output', 'Vivek Kumar Singh, Rajesh Piryani, Satya Swarup Srichandan', 'Scientometrics', 2020, '10.1007/s11192-020-03472-y', 'https://link.springer.com/article/10.1007/s11192-020-03472-y', 'Open Access has emerged as an important movement worldwide during the last decade. There are several initiatives now that persuade researchers to publish in open access journals and to archive their pre- or post-print versions of papers in repositories. Institutions and funding agencies are also promoting ways to make research outputs available as open access. This paper looks at open access levels and patterns in research output from India by computationally analyzing research publication data obtained from Web of Science for India for the last 5 years (2014–2018). The corresponding data from other connected platforms—Unpaywall and Sci-Hub—are also obtained and analyzed. The results obtained show that about 24% of research output from India, during last 5 years, is available in legal forms of open access as compared to world average of about 30%. More articles are available in gold open access as compared to green and bronze. On the contrary, more than 90% of the research output from India is available for free download in Sci-Hub. We also found disciplinary differentiation in open access, but surprisingly these patterns are different for gold–green and black open access forms. Sci-Hub appears to be complementing the legal gold–green open access for less covered disciplines in them. The central institutional repositories in India are found to have low volume of research papers deposited.', '', '', '', 'Scholary Databases,'),
(2, 'Gender and Research Publishing Analyzed through the Lenses of Discipline, Institution Types, Impact and International Collaboration: A Case Study from India', 'Jyoti Paswan, Vivek Kumar Singh', 'Scientometrics', 2020, '10.1007/s11192-020-03398-5', 'https://link.springer.com/article/10.1007/s11192-020-03398-5', 'Higher participation of women in higher education and research is a very important development goal in many countries across the world, with several countries creating special initiatives and schemes to increase participation of women in higher education and research. This article looks at a case study from India and aims to characterize the participation of women in research, by analysing the parameters of institution-type, discipline, citation impact and international collaboration. Research publication data from 50 most productive Indian institutions, along with data for 5 major institution systems, for a period of 10 years (2008–2017), as indexed in Web of Science, is obtained as sample data and analysed. Results obtained show that participation of women is found to vary in different disciplines, with biology (37%), agriculture science (32%), social science (31%) and medical science (32%) having relatively higher number of female 1st authored papers as compared to engineering (20%), information science (21%) and mathematics (22%). It is also observed that institutions specializing in medical sciences and social science have relatively better participation of women. In terms of location of institution in a big metropolitan city or an urban area, it was found that there do not exist any significant differentiation in levels of participation of women in research between institutions located in bigger cities or smaller towns. Further, analysis of citation and collaboration patterns show that though male authored papers have an edge in citation impact, women researchers get more internationally collaborated papers.', '123', '1', '497-515', 'Research Productivity , Gender in Publishing '),
(3, 'Social Media Coverage of Research Output from 100 Most Productive Institutions in India', 'Tanu Solanki, Mousumi Karmakar, Sumit Kumar Banshal, Vivek Kumar Singh', 'Journal of Scientometric Research', 2019, '10.5530/jscires.8.3.30', 'http://www.jscires.org/article/324', 'In the modern age of connected world and social media, research outcomes that are of direct interest & relevance to society are increasingly being shared and disseminated in news sources and social media platforms. Some studies have found that social media mentions of research papers can be an early indicator of their impact. India, which is now among the top 10 knowledge producers in the world, has more than 900 Universities that contribute to its research output. This paper tries to analyze as to what proportion of research output from the 100 most productive Indian institutions gets social media coverage. It is found that, while average social media coverage for India is around 28.5%, the coverage varies between 5% to 60% for different institutions. It is also observed that research output from institutions in some specific disciplines (such as Medical Science and Biological Science) attract more social media coverage as compared to others. The possible impact of geographical location (in a metro city) of an institution on social media coverage of its research output is analyzed as well. The findings present useful insight about social media coverage of research output of Indian institutions, which may be a proxy for societal relevance of the research work, and also indicate that suitable mechanisms need to be designed to promote dissemination of research results from Indian institutions in popular social media platforms.', '8', '3', '143-149', 'Research Productivity , Altmetrics , Country/Region Study'),
(4, 'Open Access Levels and Patterns in Scholarly Articles from India', 'Rajesh Piryani, Jyoti Dua, Vivek Kumar Singh', 'Current Science', 2019, '10.18520/cs/v117/i9/1435-1440', 'https://www.currentscience.ac.in/Volumes/117/09/1435.pdf', 'Open access (OA) has emerged as an important movement worldwide during the last decade. There are several calls now that not only persuade researchers to publish in OA journals, to archive their pre-  or  post-print  versions  of  papers  in  repositories,  but  also  institutions  and  funding  agencies  to  promote  OA  of  research  publications.  This  article  examines  OA  levels  and  patterns  in  research  output  by  computationally  analysing  research  publication  data  obtained  from  the  Web  of  Science  for India during the last five years (2014–2018). Results obtained show that about 24% of research output  from  India,  during  the  last  five  years,  is  available  in  OA  compared  to  world  average  of  about  30%.  More  articles  are  available  in  gold  OA  compared  to  green  and  bronze  OA.  Furthermore,  OA  levels  vary  in  different  disciplines,  with  medical  science,  physics  and  biology  having  higher percentage of their articles available as OA as compared to those like arts and humanities, social science and (surprisingly) information science. ', '117', '9', '1435-1440', 'Scholarly Databases , Country/Region Study'),
(5, 'How much Research Output from India gets Social Media Attention?', 'Sumit Kumar Banshal, Vivek Kumar Singh, Pranab Kumar Muhuri, Philipp Mayr', 'Current Science', 2019, '10.18520/cs/v117/i5/753-760', 'https://www.currentscience.ac.in/Volumes/117/05/0753.pdf', 'Scholarly  articles  are  now  increasingly  being  mentioned  and  discussed  in  social  media  platforms,  sometimes even as pre- or post-print version uploads. Measures of social media mentions and coverage  are  now  emerging  as  an  alternative  indicator  of  impact  of  scholarly  articles.  This  article  aims to explore how much scholarly research output from India is covered in different social media platforms, and how similar or different it is from the world average. It also analyses the discipline-wise variations in coverage and altmetric attention for Indian research output, including a comparison  with  the  world  average.  Results  obtained  show  interesting  patterns.  Only  28.5%  of  the  total    research output from India is covered in social media platforms, which is about 18% less than the world average. ResearchGate and Mendeley are the most popular social media platforms in India for scholarly article coverage. In terms of discipline-wise variation, medical sciences and biological sciences have relatively higher coverage across different platforms compared to disciplines like  information science and engineering.', '117', '5', '753-760', 'Country/Region Study , Altmetrics'),
(6, 'Comparing Research Performance of Private Universities in India with IITs, Central Universities and NITs', 'Sumit Kumar Banshal, Vivek Kumar Singh,  Philipp Mayr', 'Current Science', 2019, '10.18520/cs/v116/i8/1304-1313', 'https://www.currentscience.ac.in/Volumes/116/08/1304.pdf', 'During the last two decades the number of private universities in India has increased significantly. According  to  AISHE  report  of  2016,  out  of  799  universities  in  India,  277  are  private  universities,  i.e.  one  out  of  every  three  universities  in  India  is  a  private  university.  A  significant  proportion  of  colleges (about 78%) are also privately managed, as they do not contribute much to research activities  and  hence  are  not  included  in  this  analysis.  Private  universities  are  now  becoming  a  major  component  of  the  Indian  higher  education  system.  Some  of  the  private  universities  are  exclusively  positioning  and  projecting  themselves  as  universities  for  high  quality  research  and  innovation.  A  few of them are now well placed in the national-level NIRF ranking framework. It is in this context that this paper presents a comparative account of research performance of the 25 most productive private  universities  with  the  set  of  Indian  Institutes  of  Technology  (IITs),  Central  Universities  (CUs)  and  National  Institutes  of  Technology  (NITs),  all  of  which  have  a  well-established  environment  and  culture  of  research.  A  set-based  comparison  methodology  is  followed.  The  results  show  good  performance  of  private  universities  in  research,  especially  in  terms  of  output  and  rate  of  growth of output. However, on quality and productivity per capita and per rupee spent, they have a long way to go to match the performance levels of well-established centrally funded higher education  institutions  of  India.  This  study  presents  detailed  scientometric  assessment  of  some  most  productive private universities in India. ', '116', '8', '1304-1313', 'Research Productivity'),
(7, 'Research Performance of the National Institutes of Technology in India', 'Sumit Kumar Banshal, Tanu Solanki, Vivek Kumar Singh', 'Current Science', 2018, '10.18520/cs/v115/i11/2025-2036', 'http://www.currentscience.ac.in/Volumes/115/11/2025.pdf', 'This article presents a bibliometric assessment of research performance of the National Institutes of Technology (NITs) in India. While many of these institutes were originally established in 1960s as Regional Engineering Colleges (RECs), they were upgraded to NITs around 2002 and later. Initially NITs  offered  only  undergraduate  programmes  in  engineering.  However,  during  the  last  decade,  several NITs have started postgraduate teaching and are focusing more on research activities. It is in this context that this article assesses the research  performance  of  NITs  during  2005–2016.  The    performance  assessment  uses  research  publication  data  obtained  from  the  Web  of  Science  index.  The  data  collected  are  computationally  analysed  to  identify  productivity,  productivity  per  capita,  rate of growth of research, international collaboration pattern, citation impact and discipline-wise distribution  of  the  research  output  for  the  NITs.  The  performance  of  NITs  is  also  viewed  vis-à-vis  two  top-performing  Indian  institutions,  namely  Indian  Institute  of  Science,  Bengaluru  and  Indian  Institute of Technology Bombay, Mumbai. A simple single-value composite ranking of research performance  of  NITs  is  also  presented  by  combining  quantity  and  quality  factors.  The  study  presents  an informative and useful account of assessment of research work in the NITs.', '115', '11', '2025-2036', 'Research Productivity , Research Productivity'),
(8, 'An Altmetric Analysis of Scholarly Articles from India', 'Sumit Kumar Banshal, Vivek Kumar Singh, Golam Kaderye, Pranab Kumar Muhuri, Belem Priego Sanchez', 'Journal of Intelligent and Fuzzy Systems', 2018, '10.3233/JIFS-169495', 'https://content.iospress.com/articles/journal-of-intelligent-and-fuzzy-systems/ifs169495', 'Scholarly articles are considered one of the primary medium for dissemination of inventions and discoveries. Traditionally, usefulness and popularity of a scholarly article has been measured in terms of citations it receives. However, in the changed research publishing landscape, where most of the publications are now available in digital form accessible through various digital libraries; new measures of measuring usefulness of scholarly articles have emerged. Nowadays, scholarly articles are easily available for access and download from various digital access portals. The use and popularity of these digital access portals has also made it possible to integrate various social media platforms with journal access and use. Most of the journals now maintain statistics about reads, number of downloads, social profile shares etc. Several newer platforms like ResearchGate, Academia and Mendeley have also become popular. Researchers now often share their articles on various such platforms and also use social media channels to disseminate their article to a wider audience. This transformed environment has allowed to track and measure usefulness and popularity of scholarly articles through alternative metrics (now popularly known as Altmetrics) as compared to traditional citation impact measures. Altmetrics attempts to derive impact of a scholarly article by using data from different kinds such as social network share, mentions, tweets etc. The use of Altmetrics varies widely from country to country and discipline to discipline. This paper attempts to present findings of an exploratory analysis of relevance of Altmetrics data through a case study of scholarly articles from India published during 2016 and indexed in Web of Science and also updated on ResearchGate. The results obtained provide an interesting insight on relatedness and correlation of presence of scholarly articles in Web of Science and ResearchGate. It is observed that about 61% papers indexed in Web of Science have an entry in ResearchGate. There are, however, disciplinary variations in presence of articles in ResearchGate. Only about 61% of the total disciplines in Web of Science are found to be covered in ResearchGate. ', '34', '5', '3111-3118', 'Research Productivity , Altmetrics , Scholarly Databases'),
(9, 'Research Performance of Central Universities in India', 'Marisha, Sumit Kumar Banshal, Vivek Kumar Singh', 'Current Science', 2017, '10.18520/cs/v112/i11/2198-2207', 'http://www.currentscience.ac.in/Volumes/112/11/2198.pdf', 'This article presents the research performance of the 39 central universities in India. The research publication  data,  indexed  in  the  Web  of  Science,  for  the  39 central universities  for  a  25-year  period(1990–2014) are used for analysis. The data are computationally analysed to identify productivity, productivity per capita, productivity per crore rupees grant, rate of growth of research output, authorship and collaboration pattern, citation impact and discipline-wise research strength of these institutions.  Research  performance  of  the central universities  is  measured  and  compared  with  two top-ranking world universities, namely University of Cambridge and Stanford University. While older well-established  big  universities  such  as  University  of  Delhi  and  Banaras  Hindu  University  perform better than newer universities, some  relatively  smaller universities,  such as the university of Hyderabad have impressive research performance. What is disturbing is that combined research output of all central universities  taken  together  is  less  than  that  of  either  of  University  of  Cambridge  or  Stanford University alone. The results also provide discipline-wise research strengths of all the universities.', '112', '11', '2198-2207', 'Research Productivity , Country/Region Study'),
(10, 'Research performance of the Indian Institutes of Technology', 'Sumit Kumar Banshal, Vivek Kumar Singh, Aparna Basu, Pranab Kumar Muhuri', 'Current Science', 2017, '10.18520/cs/v112/i05/923-932', 'http://www.currentscience.ac.in/Volumes/112/05/0923.pdf', 'This article presents  a  computational  analysis  of  the  research  performance  of  16  relatively  older Indian  Institutes  of  Technology  (IITs)  in  India.  The  research  publication  data  indexed  in  Web  of Science for all the 16 IITs is used for the analysis. The data is computationally analysed to identify productivity, productivity per capita, rate of growth of research output, authorship and collaboration  pattern,  citation  impact  and  discipline-wise  research  strengths  of  the  different  IITs.  The  re-search performances of the IITs have been compared with those of two top ranking engineering andtechnology  institutions  of  the  world  (MIT-USA  and  NTU-Singapore)  and  most  cited  papers  from these  IITs  have  also  been  identified.  The  analytical  results  are  expected  to  provide  a  informative, up-to-date and useful account of research performance assessment of the IITs.', '112', '5', '923-932', 'Country/Region Study , Research Productivity'),
(11, 'Designing a Composite Index for Research Performance Evaluation at the National or Regional Level: Ranking Central Universities in India', 'Aparna Basu, Sumit Kumar Banshal, Khushboo Singhal, Vivek Kumar Singh', 'Scientometrics', 2016, '10.1007/s11192-016-1935-0', 'http://link.springer.com/article/10.1007/s11192-016-1935-0', 'It is now generally accepted that institutions of higher education and research, largely publicly funded, need to be subjected to some benchmarking process or performance evaluation. Currently there are several international ranking exercises that rank institutions at the global level, using a variety of performance criteria such as research publication data, citations, awards and reputation surveys etc. In these ranking exercises, the data are combined in specified ways to create an index which is then used to rank the institutions. These lists are generally limited to the top 500–1000 institutions in the world. Further, some criteria (e.g., the Nobel Prize), used in some of the ranking exercises, are not relevant for the large number of institutions that are in the medium range. In this paper we propose a multidimensional ‘Quality–Quantity’ Composite Index for a group of institutions using bibliometric data, that can be used for ranking and for decision making or policy purposes at the national or regional level. The index is applied here to rank Central Universities in India. The ranks obtained compare well with those obtained with the h-index and partially with the size-dependent Leiden ranking and University Ranking by Academic Performance. A generalized model for the index using other variables and variable weights is proposed.', '107', '3', '1171-1193', 'Indicators , Research Productivity , Country/Region Study'),
(12, 'Measuring the University-Industry-Government Collaboration in Indian Research Output', 'Rupika, Ashraf Uddin, Vivek Kumar Singh', 'Current Science', 2016, '10.18520/cs/v110/i10/1904-1909', 'https://www.currentscience.ac.in/Volumes/110/10/1904.pdf', 'Universities,  industry  and  government  organizations  all  play  an  important  role  in  growth  and development of knowledge-based economies in the modern era. These institutions also play a significant role in knowledge creation and its deployment to the benefit of society at large. In this article,we  measure  and  characterize  the  university–industry–government  (UIG)  relationship in  the  research and innovation landscape of India. Research output data for 10 years (2005–14) obtained from Web of Science have been analysed to measure collaboration among different actors of the UIG collaboration  network.  We  have  also  measured  the  collaboration  variations  across  different  disciplines  and identified  significant  UIG  institutional  networks.  The  article  presents  useful  output  and  analysis, and an informative account of the UIG collaboration network at present.', '110', '10', '1904-1909', 'Country/Region Study , Research Productivity , Collaboration Study'),
(13, 'A Sciento-text Framework to Characterize Research Strength of Institutions at Fine-grained Thematic Area Level', 'Ashraf Uddin, Jaideep Kumar, Marisha,  Vivek Kumar Singh', 'Scientometrics', 2016, '10.1007/s11192-016-1836-2 ', 'http://link.springer.com/article/10.1007%2Fs11192-016-1836-2', 'This paper presents a Sciento-text framework to characterize and assess research performance of leading world institutions in fine-grained thematic areas. While most of the popular university research rankings rank universities either on their overall research performance or on a particular subject, we have tried to devise a system to identify strong research centres at a more fine-grained level of research themes of a subject. Computer science (CS) research output of more than 400 universities in the world is taken as the case in point to demonstrate the working of the framework. The Sciento-text framework comprises of standard scientometric and text analytics components. First of all every research paper in the data is classified into different thematic areas in a systematic manner and then standard scientometric methodology is used to identify and assess research strengths of different institutions in a particular research theme (say Artificial Intelligence for CS domain). The performance of framework components is evaluated and the complete system is deployed on the Web at url: www.universityselectplus.com. The framework is extendable to other subject domains with little modification.', '106', '3', '1135-1150', 'Indicators , Research Productivity'),
(14, 'Research Competitiveness of Indian Institutes of Science Education & Research (IISERs)', 'Tanu Solanki, Ashraf Uddin, Vivek Kumar Singh', 'Current Science', 2016, '10.18520/cs/v110/i3/307-310', 'http://www.currentscience.ac.in/Volumes/110/03/0307.pdf', 'This article describes our effort to measure the research competitiveness of Indian Institutes of Science  Education  and  Research  (IISERs)  through  a  scientometric  analysis  of  their  research  output during  the  last  five  years  (2010–14).  The  research  output  indexed  in  Web  of  Science  of  the  five recently  established  IISERs has  been  obtained  and  analysed  computationally  to  identify  growth trends,  per  capita  output,  authorship  and  collaboration patterns,  citation  impact,  average  citation per  paper,  etc.  The  research  performance  of  IISERs  is  also  compared  with the Indian  Institute  of Science and the Indian Institute of Technology system to obtain an assessment of their research potential. Thus the article presents a useful and detailed analytical account of research potential and competitiveness of IISERs.', '110', '3', '307-310', 'Research Productivity , Collaboration Study , Country/Region Study'),
(15, 'Computer Science Research: The Top 100 Institutions in India and in the World', 'Vivek Kumar Singh, Ashraf Uddin, David Pinto', 'Scientometrics', 2015, '10.1007/s11192-015-1612-8', 'http://link.springer.com/article/10.1007/s11192-015-1612-8', 'This paper aims to perform a detailed scientometric and text-based analysis of Computer Science (CS) research output of the 100 most productive institutions in India and in the world. The analytical characterization is based on research output data indexed in Scopus during the last 25 years period (1989–2013). Our computational analysis involves a two-dimensional approach involving the standard scientometric methodology and text-based analysis. The scientometric characterization aims to assess CS domain research output in leading Indian institutions vis-à-vis the leading world institutions and to bring out the similarities and differences among them. It involves analysis along traditional scientometric indicators such as total output, citation-based impact assessment, co-authorship patterns, international collaboration levels etc. The text-based characterization aims to identify the key research themes and their temporal trends for the two sets. The key contribution of the experimental work is that it’s an analytical characterization of its kind, which identifies characteristic similarities and differences in CS research landscape of Indian institutions vis-à-vis world institutions.', '104', '2', '529-553', 'Research Productivity , Country/Region Study , '),
(16, 'A Quantity-Quality Composite Ranking of Indian Institutions in Computer Science Research', 'Ashraf Uddin, Vivek Kumar Singh', 'IETE Technical Review', 2015, '10.1080/02564602.2015.1010614', 'http://www.tandfonline.com/doi/abs/10.1080/02564602.2015.1010614#preview', 'This paper presents our proposed framework and experimental results on a quantity–quality composite performance assessment and ranking of Indian institutions in computer science (CS) research. We have tried to rank the 100 most productive Indian institutions in CS research on a composite single value rank derived from both ‘quantity’ and ‘quality’ parameters. Our work follows a standard scientometric methodology and uses data obtained from Scopus for 25 year period (1989–2013). The data are computationally analysed on relevant primary and secondary indicators and a composite quantity–quality ranking of research performance of Indian institutions in CS domain is computed. The proposed framework and the composite ranks obtained are analysed, evaluated and correlated with individual indicators and other recent work. The results obtained present a comprehensive analysis of research competitiveness of Indian institutions in CS research, both relative to each other and with the world top, and present inferences useful for policy makers, funding agencies, prospective students, and the CS community at large.', '32', '4', '273-283', 'Indicators , Country/Region Study , Altmetric , '),
(17, 'Mapping the Computer Science Research in SAARC Countries', 'Ashraf Uddin, Vivek Kumar Singh', 'IETE Technical Review', 2014, '10.1080/02564602.2014.947527', 'http://www.tandfonline.com/doi/full/10.1080/02564602.2014.947527#preview', 'This paper presents a scientometric and keyword-based analysis of research work done in the discipline of computer science (CS) in the SAARC region during the last 25 years. We have performed a detailed computational analysis of bibliometric and textual data for publications originating from the SAARC countries indexed in Scopus. Our analysis measures and presents findings on total CS research output of the SAARC countries, global share and rank, growth trends and impact, collaboration levels within and outside of SAARC countries, top-ranking institutions and individuals in the region, most preferred journals in the region, and a text-based research topic trend. The analytical results provide a useful mapping of CS research work in the SAARC region. The results are correlated with other demographic and economic indicators of the SAARC countries, and present inferences useful for determining funding patterns and policy formulation for scientific research in CS domain.', '31', '4', '287-296', 'Country/Region Study , Scholarly Databases , Collaboration Study'),
(18, 'Measuring Research Output and Collaboration in South Asian Countries', 'Ashraf Uddin, Vivek Kumar Singh', ' Current Science', 2014, '', 'https://www.currentscience.ac.in/Volumes/107/01/0031.pdf', 'This article presents a scientometric analysis of academic research output, growth trend, citation &impact,  and  research  collaboration  levels  in  the  South  Asian  region.  The  analysis  is  done  on several  important  parameters  such  as  total  research  production,  global  share  and  rank,  subject categories,  citation  impact,  in  and  out-region  citation  patterns,  and  inter-country  collaborations. The  economic  indicators  relating  to  higher  education and  research for  the  countries  in  the  region are correlated with the analytical results. It also analyses the research growth and maturity levels for the region. In summary, it tries to map the academic research status in the South Asian region, including details about the countries in the region.', '107', '1', '31-38', 'Collaboration Study , Country/Region Study , Research Productivity , Citation Studies'),
(19, 'The Information Technology Knowledge Infrastructure in South Asia', 'Khushboo Singhal, Sumit Banshal, Ashraf Uddin, Vivek Kumar Singh', 'Journal of Scientometric Research', 2014, '10.4103/2320-0057.153578', 'https://jscires.org/article/96', 'The South Asian region habitat about 17% of the world population and it is very important that we ensure development and prosperity of the citizens in the region for a developed and prosperous world. Information technology (IT) is considered as the technology of the modern world, one which has virtually become necessary for economic and scientific development of a nation. IT sector now plays a very important role in all spheres of life and has a measurable impact on the development trajectory of a country. The South Asian countries, despite lagging behind in Science and Technology sector development during the second half of the 20th century, made noticeable progress in the IT sector in the recent past. IT has gradually become one of the largest services sector contributors to economies of the region and one of the major employment providers. However, at the same time, it is also true that the region lacs the effort toward the development of original hardware and software products and services. Most of the products (both hardware and software) are being designed, conceptualized, and manufactured elsewhere, and the South Asian region is merely contributing to the operational part by virtue of utilizing abundant manpower. It is in this context that we have tried to measure the level of preparedness of the core strength of the IT knowledge sector and the level of research efforts in this sector towards creating original algorithms, products, and services. The paper explores and measures the IT knowledge infrastructure and the research competence of South Asian countries and provides a detailed analysis of the scenario.', '3', '3', '134-142', 'Country/Region Study , Collaboration Study');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `publications`
--
ALTER TABLE `publications`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `publications`
--
ALTER TABLE `publications`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
